# Generated by Django 5.0.6 on 2024-11-19 09:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=100, unique=True)),
                ('vat_no', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Director', 'Director'), ('Finance Manager', 'Finance Manager'), ('General Manager', 'General Manager'), ('Normal User', 'Normal User')], default='Normal User', max_length=20)),
                ('designation', models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Team Lead', 'Team Lead'), ('Other', 'Other')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Director', 'Director'), ('Finance Manager', 'Finance Manager'), ('General Manager', 'General Manager'), ('Normal User', 'Normal User')], max_length=20)),
                ('permissions', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
